### ISSUE TITLE
自動応答のカスタマイズ

### ISSUE THREAD

**Issue by ringo360** [ringo360/Discord.js_Bot#35]

**Comment by ringo360** [comment]
![image](https://github.com/TeamSekai/Sekai.Explode/assets/105296365/47d780d7-d679-4149-8338-8f2c3d93233b)
@takejohn 's idea ✨

**Comment by takejohn** [comment]
I'll work on this

**Comment by ringo360** [comment]
Thx! completed in #46 ...
