### ISSUE TITLE
 /random_num コマンドに振るサイコロの数を指定できるようにしたい

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#37]
**このリクエストは問題に関連していますか？**
問題なんかねぇよ

**あなたが望む解決策を教えてください。**
オプションdiceを追加して乱数を生成して加算

**あなたが検討している代替案の記述**
同じ分布の乱数が生成できたら他のアルゴリズムでいい

**補足説明**
ない

**Comment by ringo360** [comment]
いいアイデア！
Projectsに追加 👍

**Comment by ringo360** [comment]
Completed in #55 . Good work!

**Comment by ringo360** [comment]
ay, we found issue
![image](https://github.com/TeamSekai/Sekai.Explode/assets/105296365/c8182ad2-b9fd-4cb8-bd67-d25a46744c37)

**Comment by ringo360** [comment]
:o: 50d100
:x: 50d99

**Comment by ringo360** [comment]
okay, fixed in #56 !
