### ISSUE TITLE
gban sync時にban理由がおかしくなる

### ISSUE THREAD

**Issue by ringo360** [ringo360/Discord.js_Bot#39]
**バグについての説明**
/gban syncを使ってユーザーのbanを行った際、理由が最初の1文字しか入力されない。

**再現方法**
1. Sekai.Explodeを追加
2. banユーザーが存在する状態で/gban syncをする
3. 監査ログを見る
4. 分かる

**期待される振る舞い(動作)**
ban理由が全て正常に表示されること

**スクリーンショット**
![image](https://github.com/TeamSekai/Sekai.Explode/assets/105296365/10cfc4cd-bed6-45b9-bdbc-3f1a39ce6b68)

**動作環境(この項目を埋めてください。):**
 - OS: Ubuntu20.04
 - Node.jsのバージョン: v18.17.1

**補足説明**
言語ファイルの影響? 前のissueと似た問題である可能性が高い

**Comment by ringo360** [comment]
@takejohn 
Can u help me?

**Comment by ringo360** [comment]
I'll work on this tomorrow

**Comment by takejohn** [comment]
[commands/globalban.js:80](https://github.com/TeamSekai/Sekai.Explode/blob/fb5083bf0c19b17e9ffcb1c8f6f26073bf0823e6/commands/globalban.js#L80) で　 `strFormat` の第2引数を配列にしていなかったことが要因ですね…
他にもこういうミスをしてそうなので `strFormat` のほうを編集する方向で行きます。

**Comment by ringo360** [comment]
fixed in #40
