### ISSUE TITLE
コードフォーマッタの導入

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#50]
**このリクエストは問題に関連していますか？**
インデントがスペースのソースコードとタブのソースコードが混在している。
セミコロンが欠けているところがある。

**あなたが望む解決策を教えてください。**
[Prettier](https://prettier.io/) などのコードフォーマッタを導入して、各自およびGitHub Actionsで実行する。

**あなたが検討している代替案の記述**
なし

**補足説明**
[ESLint](https://eslint.org/) も併用するといいかもしれない

**Comment by ringo360** [comment]
Pretitterには賛成

**Comment by ringo360** [comment]
*Prettier

**Comment by ringo360** [comment]
prob completed in #53

**Comment by takejohn** [comment]
GitHub Actions :eyes:

**Comment by ringo360** [comment]
必要性を感じた頃にやる(
