### ISSUE TITLE
check-hostを使用するコマンドの統一

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#52]
**このリクエストは問題に関連していますか？**
/checkping で ping のチェック、/dev03 で tcp のチェックで分かりづらい気がする。

**あなたが望む解決策を教えてください。**
/check コマンドを作成してサブコマンド (/check ping, /check tcp) にする。

**あなたが検討している代替案の記述**
あるいは /dev03 を /checktcp に変更する。

**補足説明**
check-{http, dns, udp} も追加したい

**Comment by ringo360** [comment]
good idea 💡

**Comment by ringo360** [comment]
Completed in #58
