### ISSUE TITLE
日時の表示コマンド

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#54]
**このリクエストは問題に関連していますか？**
曜日が分からない人がいる

**あなたが望む解決策を教えてください。**
- [x] /date コマンドの追加
- [x] /cal コマンドの追加

**あなたが検討している代替案の記述**
なし

**補足説明**
なし

**Comment by ringo360** [comment]
ほしいっちゃほしい

**Comment by ringo360** [comment]
`/cal`のデザイン 💭

**Comment by takejohn** [comment]
多分 `packages/misc/commands/` にこんな感じのファイルを追加するだけ！
good first issue!!!
```js
export default new SimpleSlashCommandBuilder("date", "時刻を表示")
    .build((i) => i.reply(new Data().toString()));
```
