### ISSUE TITLE
関連コマンドをまとめる

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#62]
**このリクエストは問題に関連していますか？**
コマンドを追加する際 `commands` ディレクトリ直下に追加するため、コマンドの関連が分かりづらい。
また、コマンドの `data` プロパティの `SlashCommandBuilder` に誤りがある場合、`command` ディレクトリ内のソースファイルをインポートするコードでエラーが発生するため、どのコマンドに問題があるかが分からない。

**あなたが望む解決策を教えてください。**
関連したコマンドを1つの単位 (ここでは `feature` と呼ぶ) にまとめて、`feature` を `features` ディレクトリ以下に配置する。
`feature` 内の `feature.json` ファイルで自動的に読み込むファイル (`index.js` など) を指定する。
`feature.json` で指定されたエントリーポイントで明示的にコマンドを登録する。
`config.json` のような設定ファイルは各 `feature` に分割する。

ディレクトリ階層のイメージ:
```
.
└── features/
    ├── feature1/
    │   ├── commands/
    │   │   ├── ping.js
    │   │   └── ...
    │   ├── feature.json
    │   └── index.js
    └── feature2/
        ├── config.json.example
        ├── commands/
        │   ├── updater.js
        │   └── ...
        ├── feature.json
        └── index.js
```

**あなたが検討している代替案の記述**
知らん

**補足説明**
実装は自分でやります。

**Comment by ringo360** [comment]
Good idea 👍

**Comment by ringo360** [comment]
I added to Project 🚀

**Comment by takejohn** [comment]
featureをパッケージにするのもいいかな

**Comment by ringo360** [comment]
Okay, completed in #64 !
