### ISSUE TITLE
LokiJS対応

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#75]
**このリクエストは問題に関連していますか？**
MongoDB入れるの面倒

**あなたが望む解決策を教えてください。**
[LokiJS](https://github.com/techfort/LokiJS)をデータベースに使用できるようにする

**あなたが検討している代替案の記述**
null

**補足説明**
null

**Comment by ringo360** [comment]
👀

**Comment by takejohn** [comment]
completed!
