### ISSUE TITLE
/uploadコマンドがファイルの種類によって使用できない

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#77]
**バグについての説明**
/uploadコマンドで一部の種類のファイルをアップロードしようとすると「内部エラー: Unsupported Media Type(415)」といって失敗する。

**再現方法**
1. ftpうんち！
2. Sekai.Explode入れるぜ！！
3. CDNで共有せんと、インターネットがおっそいなあ……
4. よし、/uploadコマンドでexeファイルを共有するぞ～～～！
5. 殺すぞボケ！！！！
6. なんでアップロードできんのやカスッ！！

**期待される振る舞い(動作)**
Sekai.Explodeの/uploadコマンドでexeファイルとかアップロードしてみる！成功！！

**スクリーンショット**
![axios issue](https://github.com/TeamSekai/Sekai.Explode/assets/105504345/be26fa36-9b6e-4ed4-9a63-9407aee94f65)

**動作環境(この項目を埋めてください。):**
 - OS: Ubuntu 22.04
 - Node.jsのバージョン: v21.7.1

**補足説明**
こんなおっそいインターネットふざけんなッ！！！はぁはぁはぁ……

**Comment by ringo360** [comment]
😭 直したい
