### ISSUE TITLE
年齢を調べるコマンドの追加

### ISSUE THREAD

**Issue by ringo360** [ringo360/Discord.js_Bot#94]
**このリクエストは問題に関連していますか？**
自分が今何歳かを忘れる致命的な問題が発生している

**あなたが望む解決策を教えてください。**
/ageで生年月日を入れて、年齢を調べる
**あなたが検討している代替案の記述**
素直に友人や親に聞く

**補足説明**
ない

**Comment by takejohn** [comment]
#54 + 日付の計算機能 :thinking:

**Comment by ringo360** [comment]
yee
